apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: https://ca-prometheus.internal.ambitiousdune-51dd5b07.koreacentral.azurecontainerapps.io
    isDefault: true
    editable: false

  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: https://ca-loki.internal.ambitiousdune-51dd5b07.koreacentral.azurecontainerapps.io
    editable: false
